# Generated by Django 5.2.6 on 2025-12-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, db_index=True, help_text='Ej: +5939XXXXXXX (opcional)', max_length=20, null=True),
        ),
    ]
